# Generated by Django 3.2 on 2021-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=10)),
                ('parcel_product_type', models.CharField(max_length=20)),
                ('parcel_weight', models.CharField(max_length=10)),
                ('parcel_dest_choice', models.CharField(max_length=20)),
                ('parcel_dest', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('deliver_address', models.CharField(max_length=120)),
                ('marchant_name', models.CharField(max_length=150)),
                ('marchant_phone', models.CharField(max_length=20)),
                ('order_status', models.CharField(default='default', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
